# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_blake3r_wrappers", use_symbols = TRUE, package_name = "blake3r")

#' @docType package
#' @usage NULL
#' @useDynLib blake3r, .registration = TRUE
NULL

hash_file_with_blake3_impl <- function(file_path) .Call(wrap__hash_file_with_blake3_impl, file_path)

hash_file_with_blake3_direct_impl <- function(file_path) .Call(wrap__hash_file_with_blake3_direct_impl, file_path)


# nolint end
